/*
 * test.js — unit tests for the Bug Report Builder's pure logic.
 * Run: node test.js
 *
 * The logic lives in the FIRST <script> block of index.html and is
 * browser-free, so we extract it, run it in a VM sandbox with stubbed
 * browser globals, and assert against the exported __bugLogic surface.
 */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');

// 1. basic document sanity: tags that must exist exactly once / be balanced
function countTag(tag) {
  const re = new RegExp('<' + tag + '[\\s>]', 'g');
  return (html.match(re) || []).length;
}
let passed = 0, failed = 0;
function ok(cond, name) {
  if (cond) { passed++; console.log('  ok - ' + name); }
  else { failed++; console.error('  FAIL - ' + name); }
}

ok(countTag('html') === 1, 'single <html>');
ok(countTag('body') === 1, 'single <body>');
ok((html.match(/<\/script>/g) || []).length === 2, 'two script blocks (logic + UI)');
ok(html.includes('id="steps"') && html.includes('id="preview"') && html.includes('id="quality"'),
   'key element ids present');
ok(!/Built by Muse|Muse AI|generated by/i.test(html), 'no AI attribution in html');

// 2. extract the logic script and run it in a sandbox
const m = html.match(/<script>([\s\S]*?)<\/script>/);
if (!m) { console.error('FAIL: no logic script block found'); process.exit(1); }

const sandbox = {
  console,
  document: { addEventListener() {}, getElementById() { return null; } },
  localStorage: { getItem() { return null; }, setItem() {} },
  navigator: {}
};
vm.createContext(sandbox);
vm.runInContext(m[1], sandbox);
const L = sandbox.__bugLogic;
ok(!!L, 'logic exported as __bugLogic');

// 3. a complete, good report
const good = {
  title: 'Cart total shows $0.00 after applying a discount code',
  os: 'Windows 11', browser: 'Chrome 131', version: 'ShopApp v2.4.1',
  network: 'Office Wi-Fi', reporter: 'QA Tester', date: '2026-10-09',
  steps: [
    'Add any item to the cart.',
    'Go to checkout and enter the discount code SAVE10.',
    'Click "Apply".'
  ],
  expected: 'The cart total updates to the discounted price.',
  actual: 'The cart total changes to $0.00 and the order can be placed for free.',
  severity: 'major',
  evidence: { reproduced: true, screenshot: true, logs: false, multiple: false },
  workaround: 'Remove the code, buy without it, then email support for a refund.'
};

const md = L.buildMarkdown(good);
ok(md.includes('# Bug: Cart total shows $0.00 after applying a discount code'), 'markdown: title heading');
ok(md.includes('**Severity:** Major'), 'markdown: severity line');
ok(md.includes('Windows 11 · Chrome 131 · ShopApp v2.4.1 · Office Wi-Fi'), 'markdown: environment line');
ok(md.includes('**Reported:** QA Tester — 2026-10-09'), 'markdown: reporter line');
ok(md.includes('## Steps to reproduce') && md.includes('1. Add any item to the cart.') && md.includes('3. Click "Apply".'),
   'markdown: numbered steps');
ok(md.includes('## Expected result') && md.includes('## Actual result'), 'markdown: expected/actual sections');
ok(md.includes('- [x] Reproduced more than once') && md.includes('- [ ] Console or network logs captured'),
   'markdown: evidence checkboxes');
ok(md.includes('## Workaround') && md.includes('email support for a refund'), 'markdown: workaround section');

const goodChecks = L.runChecks(good);
const notOk = goodChecks.filter(c => c.level !== 'ok');
ok(notOk.length === 0, 'complete report passes every check (' + notOk.map(c => c.message).join('; ') + ')');

// 4. broken reports get flagged
const empty = L.blankReport();
const emptyErrs = L.runChecks(empty).filter(c => c.level === 'error');
ok(emptyErrs.length >= 5, 'blank report raises errors (' + emptyErrs.length + ')');
ok(L.runChecks(Object.assign({}, empty, { title: 'bug' })).some(c => c.level === 'error'),
   'vague one-word title is an error');

const same = Object.assign({}, good, { actual: good.expected });
ok(L.runChecks(same).some(c => c.level === 'error' && /identical/i.test(c.message)),
   'identical expected/actual is an error');

const twoSteps = Object.assign({}, good, { steps: ['Open the cart.', 'Apply the code.'] });
ok(L.runChecks(twoSteps).some(c => c.level === 'warn' && /fewer than 3/i.test(c.message)),
   'short step list warns');

const noSev = Object.assign({}, good, { severity: '' });
ok(L.runChecks(noSev).some(c => c.level === 'error' && /severity/i.test(c.message)),
   'missing severity is an error');

// 5. helpers
ok(L.filenameFor('Cart total: $0!!') === 'bug-cart-total-0.md', 'filename slug from title');
ok(L.filenameFor('   ') === 'bug-report.md', 'blank title falls back to bug-report.md');
ok(L.escapeMd('#hashtag `code`') === '\\#hashtag \\`code\\`', 'markdown metachar escaping');
ok(L.severityLabel('blocker') === 'Blocker' && L.severityLabel('') === 'Not set', 'severity labels');

// 6. shipped examples must themselves be fileable
ok(Array.isArray(L.EXAMPLES) && L.EXAMPLES.length === 2, 'two examples ship with the app');
L.EXAMPLES.forEach((ex, i) => {
  const errs = L.runChecks(ex).filter(c => c.level === 'error');
  ok(errs.length === 0, 'example ' + (i + 1) + ' passes all checks (' + errs.map(c => c.message).join('; ') + ')');
  ok(ex.steps.length >= 3, 'example ' + (i + 1) + ' has 3+ steps');
});

console.log('\n' + passed + ' passed, ' + failed + ' failed');
process.exit(failed ? 1 : 0);
