/*
 * test.js — unit tests for the Known Error Database's pure logic.
 * Run: node test.js
 *
 * The logic lives in the FIRST <script> block of index.html and is
 * browser-free, so we extract it, run it in a VM sandbox with stubbed
 * browser globals, and assert against the exported __kedbLogic surface.
 */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');

// 1. basic document sanity: tags that must exist exactly once / be balanced
function countTag(tag) {
  const re = new RegExp('<' + tag + '[\\s>]', 'g');
  return (html.match(re) || []).length;
}
let passed = 0, failed = 0;
function ok(cond, name) {
  if (cond) { passed++; console.log('  ok - ' + name); }
  else { failed++; console.error('  FAIL - ' + name); }
}

ok(countTag('html') === 1, 'single <html>');
ok(countTag('body') === 1, 'single <body>');
ok((html.match(/<\/script>/g) || []).length === 2, 'two script blocks (logic + UI)');
ok(html.includes('id="recordList"') && html.includes('id="search"') &&
   html.includes('id="detailModal"') && html.includes('id="formModal"') &&
   html.includes('id="stats"'), 'key element ids present');
ok(!/Built by Muse|Muse AI|generated by|AI assistant/i.test(html), 'no AI attribution in html');

// 2. extract the logic script and run it in a sandbox
const m = html.match(/<script>([\s\S]*?)<\/script>/);
if (!m) { console.error('FAIL: no logic script block found'); process.exit(1); }

const sandbox = {
  console,
  document: { addEventListener() {}, getElementById() { return null; } },
  localStorage: { getItem() { return null; }, setItem() {} },
  navigator: {}
};
vm.createContext(sandbox);
vm.runInContext(m[1], sandbox);
const L = sandbox.__kedbLogic;
ok(!!L, 'logic exported as __kedbLogic');

// 3. seed data
const seeds = L.seedRecords();
ok(Array.isArray(seeds) && seeds.length === 6, 'six seed records');
ok(seeds.every(r => L.validateRecord(r).length === 0), 'all seed records valid');
ok(seeds.every(r => /^KE-\d{4}$/.test(r.id)), 'seed ids look like KE-0001');

// 4. validation
const badTitle = Object.assign({}, seeds[0], { title: '   ' });
ok(L.validateRecord(badTitle).some(e => /title/i.test(e)), 'rejects blank title');
const badCat = Object.assign({}, seeds[0], { category: 'Nope' });
ok(L.validateRecord(badCat).some(e => /category/i.test(e)), 'rejects bad category');
const badWa = Object.assign({}, seeds[0], { workaround: ['  '] });
ok(L.validateRecord(badWa).some(e => /workaround/i.test(e)), 'rejects empty workaround');
const badSym = Object.assign({}, seeds[0], { symptoms: '' });
ok(L.validateRecord(badSym).some(e => /symptom/i.test(e)), 'rejects blank symptoms');

// 5. id generation
ok(L.nextId(seeds) === 'KE-0007', 'nextId after seeds is KE-0007');
ok(L.nextId([]) === 'KE-0001', 'nextId on empty list is KE-0001');

// 6. search
ok(L.searchRecords(seeds, 'vpn').some(r => r.id === 'KE-0001'), 'search "vpn" finds KE-0001');
ok(L.searchRecords(seeds, '809').some(r => r.id === 'KE-0001'), 'search "809" (error text) finds KE-0001');
ok(L.searchRecords(seeds, 'credential manager').length === 2, 'search "credential manager" finds 2 records');
ok(L.searchRecords(seeds, 'screen share').some(r => r.id === 'KE-0006'), 'search matches workaround step text');
ok(L.searchRecords(seeds, '').length === 6, 'empty query returns all');
ok(L.searchRecords(seeds, 'zzznothing').length === 0, 'no-match query returns empty');

// 7. filters
ok(L.filterRecords(seeds, { category: 'Printing' }).length === 1, 'filter by category');
ok(L.filterRecords(seeds, { severity: 'P2' }).length === 3, 'filter by severity P2 -> 3');
ok(L.filterRecords(seeds, { status: 'Resolved permanently' }).length === 1, 'filter by status');
ok(L.filterRecords(seeds, {}).length === 6, 'no filters returns all');
ok(L.filterRecords(seeds, { category: 'Email', severity: 'P3' })[0].id === 'KE-0002', 'combined filters');

// 8. sorting
const bySev = L.sortRecords(seeds, 'severity');
ok(bySev[0].severity === 'P2' && bySev[bySev.length - 1].severity === 'P4', 'severity sort: P1-first ordering');
ok(L.sortRecords(seeds, 'reported')[0].id === 'KE-0002', 'reported sort: most reported first (KE-0002, 41x)');
const byUpd = L.sortRecords(seeds, 'updated');
ok(byUpd[0].lastUpdated >= byUpd[byUpd.length - 1].lastUpdated, 'updated sort: newest first');

// 9. stats
const s = L.stats(seeds);
ok(s.total === 6 && s.workaround === 4 && s.inProgress === 1 && s.resolved === 1, 'stats by status (4/1/1)');

// 10. export / import round-trip
const exported = L.exportJSON(seeds);
ok(JSON.parse(exported).records.length === 6, 'exportJSON has 6 records');
const back = L.importJSON(exported);
ok(back.length === 6 && back[0].id === 'KE-0001', 'importJSON round-trips exportJSON');
ok(L.importJSON(JSON.stringify(seeds)).length === 6, 'importJSON accepts a bare array');
let threw = false;
try { L.importJSON('{nope'); } catch (e) { threw = /valid JSON/i.test(e.message); }
ok(threw, 'importJSON rejects malformed JSON with a clear message');
threw = false;
try { L.importJSON(JSON.stringify([{ id: 'KE-9999' }])); } catch (e) { threw = /invalid record/i.test(e.message); }
ok(threw, 'importJSON rejects records that fail validation');

// 11. helpers
ok(L.escapeHtml('<script>alert("x")</script>') === '&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;', 'escapeHtml escapes markup');
ok(/^\d{4}-\d{2}-\d{2}$/.test(L.todayISO()), 'todayISO is YYYY-MM-DD');
ok(L.SEVERITY_LABEL.P1 === 'Critical' && L.SEVERITY_LABEL.P4 === 'Low', 'severity labels');

console.log('\n' + passed + ' passed, ' + failed + ' failed');
process.exit(failed ? 1 : 0);
